# -*- coding: utf-8 -*-
"""script

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mdi6Ove0E0fYDz6ySytqGqMiz60YzEo2
"""



from flask import Flask, request, render_template, jsonify
import pandas as pd
import sys
import logging
from errors import InvalidUsage

app = Flask(__name__)


df_percent = pd.read_excel('zomato_processed.xlsx')

df_percent.set_index('name', inplace=True)

df_percent = df_percent.drop('Unnamed: 0', axis=1)

indices = pd.Series(df_percent.index)

df1 = pd.read_excel('similar_indices.xlsx')

df1 = df1.set_index('idx')

@app.route('/')
def home():
    return render_template('home.html')

@app.errorhandler(InvalidUsage)
def handle_invalid_usage(error):
    response = jsonify(error.to_dict())
    response.status_code = error.status_code
    return response

@app.route('/recommend', methods=['POST'])
def recommend():
    
    recommend_restaurant = []
    name = request.form['Restaurant']

    
    if name.lower() in (a.lower() for a in indices.values):
    
        idx = indices[indices == name.title()].index[0]

        
   
        top30_indexes = df1[df1.index==idx]['similar_indices'].values[0]
        value = top30_indexes
        if isinstance(value, str):
  
            temp=[]
            
            l=[]
            k=[]

            value = value.replace('[','').replace(']','').replace('\'','')
            l+=value.split(',')
            for i in l:
              k+=i.split(',')
            top30_indexes=k

        
        for each in top30_indexes:
            each = int(each)
        
            recommend_restaurant.append(list(df_percent.index)[each])
        
    
 
        df_new = pd.DataFrame(columns=['cuisines', 'mean_ratings', 'cost','location'])
    
   
        for each in recommend_restaurant:
            df_new = df_new.append(pd.DataFrame(df_percent[['cuisines','mean_ratings', 'cost','location']][df_percent.index == each].sample()))
    
        
        df_new = df_new.drop_duplicates(subset=['cuisines','mean_ratings', 'cost','location'], keep=False)
        df_new = df_new.sort_values(by='mean_ratings', ascending=False)
    
        
        df_new = df_new.rename(columns={'cuisines':'Cuisines','mean_ratings':'Average Normalized Rating on Zomato','cost':'Cost for 2 People', 'location':'Location'})
    
        return render_template('home.html',prediction_text='TOP %s RESTAURANTS LIKE %s WITH SIMILAR REVIEWS: ' % (str(len(df_new)), name.upper()) ,tables=[df_new.to_html(classes='data', header=True)])
    raise InvalidUsage('This Restaurant name does not exist. Kindly enter proper full name, eg : (Meghana Foods) instead of (Meghana)', status_code=410)


if __name__=='__main__':
    app.run(debug=True)